Make TLPToggle use tlp start when it can so laptop can manage modes on ac connect/disconnect

diff --git a/Scripts/TLPToggle b/Scripts/TLPToggle
--- a/Scripts/TLPToggle
+++ b/Scripts/TLPToggle
@@ -1,45 +1,30 @@
 #!/bin/bash
 
-CMode=$(cat /run/tlp/manual_mode || cat /run/tlp/last_pwr)
-Wrongpass=0 #first time run
-
-if [[ $CMode = 1 ]]; then
-    CMode="BAT" #changes battery to BAT when checking TLP mode
+if [[ $(cat /run/tlp/last_pwr) = 1 ]]; then
+    CMode="BAT" # Current mode
+    NMode="ac"  # Next mode for tlp
+    state="off" # Next mode for kdialog text
 else
     CMode="AC"
+    NMode="bat"
+    state="on"
 fi
 
-while true; do  #Loop makes sure password dialog appears every time a failed attempt occurs
-    if ! sudo true || ! sudo -n true; then
-        if [[ $Wrongpass = 0 ]]; then
-            password=$(kdialog --title "Toggle($CMode)" --password "Enter password")
-        else
-            password=$(kdialog --title "Toggle($CMode)" --password "Try Again") #Changes prompt when an incorrect password is entered
-        fi
+while true; do  # Loop makes sure password dialog appears every time a failed attempt occurs
+    if [[ -z $dialog ]] && ! sudo true || ! sudo -n true; then
+        password=$(kdialog --title "Toggle($CMode)" --password "${dialog:-Enter Password}")
     fi
-    if [[ $? = 0 ]]; then #checks if ok or cancel was selected
-        echo "Selected: OK"
-        if [[ $CMode = "AC" ]]; then    #Checks for the current mode and toggles it in the following statements
-            echo "Changing TLP to BAT mode"
-            if echo "$password" | sudo -S tlp bat; then
-                kdialog --title "TLP mode BAT" --passivepopup "Power Savings on" 3
-                break
-            else
-                echo "Wrong password entered"
-                Wrongpass=1
-            fi
+    if [[ $? = 0 ]]; then # Checks if ok or cancel was selected
+        if [[ -e /run/tlp/manual_mode ]]; then
+            AMode="start"
+        fi
+        if echo "$password" | sudo -S tlp "${AMode:-$NMode}"; then
+            kdialog --title "TLP mode ${NMode^^}" --passivepopup "Power Savings $state" 3
+            break
         else
-            echo "Changing TLP to AC mode"
-            if echo "$password" | sudo -S tlp ac; then
-                kdialog --title "TLP mode AC" --passivepopup "Power Savings off" 3
-                break
-            else
-                echo "Wrong password entered"
-                Wrongpass=1
-            fi
+            dialog="Try Again"
         fi
     else
-        echo "Selected: Cancel"
         break
     fi
 done
